import { matchesQuery } from "./matching.js";
import type { CommerceProvider, MockCatalogItem, NormalizedOffer } from "./types.js";
import { withCatalogMetadata } from "./catalogMetadata.js";

export class ZeptoProvider implements CommerceProvider {
  name = "Zepto";
  slug = "zepto";

  async search(query: string): Promise<NormalizedOffer[]> {
    if (!query.trim()) {
      return [];
    }

    return this.getCatalog()
      .filter((item) => matchesQuery(item, query))
      .map((item) => ({
        providerName: this.name,
        providerSlug: this.slug,
        ...item,
        searchAliases: undefined,
      }));
  }

  getCatalog(): MockCatalogItem[] {
    return withCatalogMetadata([
      {
        productName: "Amul Taaza Toned Milk 1L",
        brand: "Amul",
        price: 56,
        deliveryFee: 19,
        platformFee: 4,
        discount: 3,
        available: true,
        deliveryMinutes: 9,
        externalId: "zepto-amul-milk-1l",
        searchAliases: ["milk", "toned milk", "amul"],
      },
      {
        productName: "Britannia Good Day Cookies 600g",
        brand: "Britannia",
        price: 99,
        deliveryFee: 19,
        platformFee: 5,
        discount: 8,
        available: true,
        deliveryMinutes: 10,
        externalId: "zepto-britannia-good-day-600g",
        searchAliases: ["biscuits", "cookies"],
      },
      {
        productName: "Tata Salt 1kg",
        brand: "Tata",
        price: 26,
        deliveryFee: 15,
        platformFee: 2,
        discount: 0,
        available: true,
        deliveryMinutes: 8,
        externalId: "zepto-tata-salt-1kg",
        searchAliases: ["salt", "tata salt"],
      },
      {
        productName: "Maggi 2-Minute Noodles Masala 70g",
        brand: "Maggi",
        price: 15,
        deliveryFee: 15,
        platformFee: 2,
        discount: 0,
        available: true,
        deliveryMinutes: 7,
        externalId: "zepto-maggi-noodles-70g",
        searchAliases: ["noodles", "instant noodles", "maggi"],
      },
      {
        productName: "Surf Excel Easy Wash Detergent 1kg",
        brand: "Surf Excel",
        price: 142,
        deliveryFee: 22,
        platformFee: 5,
        discount: 12,
        available: true,
        deliveryMinutes: 14,
        externalId: "zepto-surf-excel-1kg",
        searchAliases: ["detergent", "laundry"],
      },
      {
        productName: "Aashirvaad Select Atta 5kg",
        brand: "Aashirvaad",
        price: 295,
        deliveryFee: 29,
        platformFee: 7,
        discount: 25,
        available: true,
        deliveryMinutes: 16,
        externalId: "zepto-aashirvaad-atta-5kg",
        searchAliases: ["atta", "wheat flour", "aashirvaad"],
      },
      {
        productName: "Britannia Brown Bread 400g",
        brand: "Britannia",
        price: 52,
        deliveryFee: 18,
        platformFee: 4,
        discount: 2,
        available: true,
        deliveryMinutes: 11,
        externalId: "zepto-britannia-bread-400g",
        searchAliases: ["bread"],
      },
      {
        productName: "Eggoz Farm Fresh Eggs 6 pcs",
        brand: "Eggoz",
        price: 75,
        deliveryFee: 18,
        platformFee: 4,
        discount: 4,
        available: true,
        deliveryMinutes: 13,
        externalId: "zepto-eggoz-eggs-6",
        searchAliases: ["eggs", "egg"],
      },
      {
        productName: "India Gate Basmati Rice 1kg",
        brand: "India Gate",
        price: 172,
        deliveryFee: 24,
        platformFee: 5,
        discount: 10,
        available: true,
        deliveryMinutes: 17,
        externalId: "zepto-india-gate-rice-1kg",
        searchAliases: ["rice", "basmati"],
      },
      {
        productName: "Madhur Pure Sugar 1kg",
        brand: "Madhur",
        price: 55,
        deliveryFee: 18,
        platformFee: 3,
        discount: 0,
        available: true,
        deliveryMinutes: 12,
        externalId: "zepto-madhur-sugar-1kg",
        searchAliases: ["sugar"],
      },
      {
        productName: "Fortune Sunlite Oil 1L",
        brand: "Fortune",
        price: 145,
        deliveryFee: 24,
        platformFee: 5,
        discount: 7,
        available: true,
        deliveryMinutes: 16,
        externalId: "zepto-fortune-oil-1l",
        searchAliases: ["cooking oil", "oil"],
      },
      {
        productName: "Lay's India's Magic Masala 52g",
        brand: "Lay's",
        price: 20,
        deliveryFee: 16,
        platformFee: 2,
        discount: 0,
        available: true,
        deliveryMinutes: 9,
        externalId: "zepto-lays-chips-52g",
        searchAliases: ["chips", "snacks"],
      },
      {
        productName: "Nescafe Classic Coffee 50g",
        brand: "Nescafe",
        price: 175,
        deliveryFee: 20,
        platformFee: 4,
        discount: 12,
        available: true,
        deliveryMinutes: 15,
        externalId: "zepto-nescafe-coffee-50g",
        searchAliases: ["coffee"],
      },
      {
        productName: "Tata Tea Premium 250g",
        brand: "Tata Tea",
        price: 132,
        deliveryFee: 20,
        platformFee: 4,
        discount: 5,
        available: true,
        deliveryMinutes: 14,
        externalId: "zepto-tata-tea-250g",
        searchAliases: ["tea", "chai"],
      },
      {
        productName: "Coca-Cola Soft Drink 750ml",
        brand: "Coca-Cola",
        price: 47,
        deliveryFee: 18,
        platformFee: 3,
        discount: 0,
        available: true,
        deliveryMinutes: 10,
        externalId: "zepto-coke-soft-drink-750ml",
        searchAliases: ["soft drink", "soft drinks", "cola"],
      },
      {
        productName: "Cadbury Dairy Milk Silk 60g",
        brand: "Cadbury",
        price: 88,
        deliveryFee: 17,
        platformFee: 3,
        discount: 4,
        available: true,
        deliveryMinutes: 10,
        externalId: "zepto-cadbury-chocolate-60g",
        searchAliases: ["chocolate"],
      },
      {
        productName: "Dove Intense Repair Shampoo 340ml",
        brand: "Dove",
        price: 325,
        deliveryFee: 20,
        platformFee: 5,
        discount: 25,
        available: true,
        deliveryMinutes: 15,
        externalId: "zepto-dove-shampoo-340ml",
        searchAliases: ["shampoo", "hair care"],
      },
      {
        productName: "Tresemme Keratin Smooth Conditioner 190ml",
        brand: "Tresemme",
        price: 218,
        deliveryFee: 20,
        platformFee: 5,
        discount: 18,
        available: true,
        deliveryMinutes: 16,
        externalId: "zepto-tresemme-conditioner-190ml",
        searchAliases: ["conditioner"],
      },
      {
        productName: "Dove Cream Beauty Bathing Bar 100g",
        brand: "Dove",
        price: 64,
        deliveryFee: 17,
        platformFee: 3,
        discount: 3,
        available: true,
        deliveryMinutes: 11,
        externalId: "zepto-dove-soap-100g",
        searchAliases: ["soap", "bathing bar"],
      },
      {
        productName: "Colgate Strong Teeth Toothpaste 200g",
        brand: "Colgate",
        price: 112,
        deliveryFee: 17,
        platformFee: 3,
        discount: 7,
        available: true,
        deliveryMinutes: 10,
        externalId: "zepto-colgate-toothpaste-200g",
        searchAliases: ["toothpaste"],
      },
      {
        productName: "Oral-B Pro Health Toothbrush Medium",
        brand: "Oral-B",
        price: 58,
        deliveryFee: 16,
        platformFee: 3,
        discount: 0,
        available: true,
        deliveryMinutes: 12,
        externalId: "zepto-oralb-toothbrush-medium",
        searchAliases: ["toothbrush", "brush"],
      },
      {
        productName: "Nivea Fresh Active Deodorant 150ml",
        brand: "Nivea",
        price: 205,
        deliveryFee: 19,
        platformFee: 4,
        discount: 15,
        available: false,
        deliveryMinutes: 18,
        externalId: "zepto-nivea-deodorant-150ml",
        searchAliases: ["deodorant", "deo"],
      },
      {
        productName: "Durex Extra Time Condoms 10 pcs",
        brand: "Durex",
        price: 252,
        deliveryFee: 17,
        platformFee: 4,
        discount: 18,
        available: true,
        deliveryMinutes: 13,
        externalId: "zepto-durex-condoms-10",
        searchAliases: ["condoms", "condom", "wellness"],
      },
      {
        productName: "Whisper Ultra Sanitary Pads XL 15 pcs",
        brand: "Whisper",
        price: 180,
        deliveryFee: 17,
        platformFee: 4,
        discount: 8,
        available: true,
        deliveryMinutes: 14,
        externalId: "zepto-whisper-pads-xl-15",
        searchAliases: ["sanitary pads", "pads"],
      },
      {
        productName: "Origami Soft Tissues 100 pulls",
        brand: "Origami",
        price: 92,
        deliveryFee: 17,
        platformFee: 3,
        discount: 4,
        available: true,
        deliveryMinutes: 12,
        externalId: "zepto-origami-tissues-100",
        searchAliases: ["tissues", "tissue"],
      },
      {
        productName: "Vim Dishwash Gel Lemon 500ml",
        brand: "Vim",
        price: 118,
        deliveryFee: 19,
        platformFee: 4,
        discount: 7,
        available: true,
        deliveryMinutes: 14,
        externalId: "zepto-vim-dishwash-500ml",
        searchAliases: ["dishwash", "dish wash"],
      },
      {
        productName: "Lizol Citrus Floor Cleaner 1L",
        brand: "Lizol",
        price: 210,
        deliveryFee: 22,
        platformFee: 4,
        discount: 16,
        available: true,
        deliveryMinutes: 16,
        externalId: "zepto-lizol-floor-cleaner-1l",
        searchAliases: ["floor cleaner", "cleaner"],
      },
      {
        productName: "Bigbasket Garbage Bags Medium 30 pcs",
        brand: "Bigbasket",
        price: 125,
        deliveryFee: 19,
        platformFee: 4,
        discount: 8,
        available: true,
        deliveryMinutes: 15,
        externalId: "zepto-garbage-bags-medium-30",
        searchAliases: ["garbage bags", "trash bags"],
      },
    ]).map((item) => ({ ...item }));
  }
}
